/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /readAppUsers:
 *   get:
 *     tags:
 *       - Administration
 *     description: readAppUsers
 *     summary: AppUsersRead
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: username
 *         description: String 
 *         in: query
 *         type: String
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    
    var readAppUsers = new Promise((resolve, reject) => {
        dao.readAppUsers(jsonObj,function(err,rows) {
            if(err) res.status(err.code).end();
            else{
                if(rows[0]===undefined) res.status(404).end();
                else{ 
                    jsonObj = rows[0];
                    resolve(jsonObj);
                }
            }
        });
    });
    
    var appAuthorities = new Promise((resolve, reject) => {
        dao.searchAppAuthorities(jsonObj,function(err,rows) {
            jsonObj.appAuthorities = rows;
            resolve(jsonObj);
        });        
    });
    
    var appContact = new Promise((resolve, reject) => {
        dao.searchAppContact(jsonObj,function(err,rows) {
            jsonObj.appContact = rows;
            resolve(jsonObj);
        });        
    });
    
    var appGroupMembers = new Promise((resolve, reject) => {
        dao.searchAppGroupMembers(jsonObj,function(err,rows) {
            jsonObj.appGroupMembers = rows;
            resolve(jsonObj);
        });        
    });
    
    var appMessage = new Promise((resolve, reject) => {
        dao.searchAppMessage(jsonObj,function(err,rows) {
            jsonObj.appMessage = rows;
            resolve(jsonObj);
        });        
    });
    
    var appPersistentLogins = new Promise((resolve, reject) => {
        dao.searchAppPersistentLogins(jsonObj,function(err,rows) {
            jsonObj.appPersistentLogins = rows;
            resolve(jsonObj);
        });        
    });
    
    var appRoom = new Promise((resolve, reject) => {
        dao.searchAppRoom(jsonObj,function(err,rows) {
            jsonObj.appRoom = rows;
            resolve(jsonObj);
        });        
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        res.status(200).send(jsonObj);
    }
    
    Promise.all([readAppUsers,appAuthorities,appContact,appGroupMembers,appMessage,appPersistentLogins,appRoom]).then(sendResult);
});

module.exports = router;
