/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppMessageNew',
    Heading:'AppMessage',
    Username:{label :'Username'},
    Jid:{label :'Jid'},
    Msgtime:{label :'Msgtime'},
    Msgtype:{label :'Msgtype'},
    Msgsubject:{label :'Msgsubject'},
    Msgtext:{label :'Msgtext'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{username:'',
        jid:'',
        msgtime:'',
        msgtype:'',
        msgsubject:'',
        msgtext:'',
        }
    }
    res.render('AppMessageNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppMessage(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppMessageNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
