/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'GeneralLedgerNew',
    Heading:'GeneralLedger',
    Id:{label :'Id'},
    AccCode:{label :'AccCode'},
    CreateDate:{label :'CreateDate'},
    Description:{label :'Description'},
    Debit:{label :'Debit'},
    Credit:{label :'Credit'},
    Posted:{label :'Posted'},
    Source:{label :'Source'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{id:'',
        accCode:'',
        createDate:'',
        description:'',
        debit:'',
        credit:'',
        posted:'',
        source:'',
        }
    }
    res.render('GeneralLedgerNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newGeneralLedger(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('GeneralLedgerNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
