/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AccountGroupRead',
    Heading:'AccountGroup',
    Id:{label :'Id'},
    Name:{label :'Name'},
    Parent:{label :'Parent'},
    Description:{label :'Description'},
    AccSectionId:{label :'AccSectionId'},
    AccountMaster:{Heading:'AccountMaster',
        Id:{header:'Id'},
        AccCode:{header:'AccCode'},
        AccName:{header:'AccName'},
        AccDescription:{header:'AccDescription'},
        AccGroupId:{header:'AccGroupId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAccountGroup?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAccountGroup = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAccountGroup(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAccountGroup');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var accountMaster = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.searchAccountMaster(jsonObj,function(err,rows) {
                jsonObj.accountMaster = rows;
                resolve(jsonObj);
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AccountGroupReadPage',parameter);
    }    
    Promise.all([readAccountGroup,accountMaster]).then(sendResult);
});

module.exports = router;
