/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ProductAccountRead',
    Heading:'ProductAccount',
    Id:{label :'Id'},
    Code:{label :'Code'},
    Name:{label :'Name'},
    Description:{label :'Description'},
    Type:{label :'Type'},
    AccStock:{label :'AccStock'},
    AccAdjgl:{label :'AccAdjgl'},
    AccPurchase:{label :'AccPurchase'},
    AccMaterial:{label :'AccMaterial'},
    AccWip:{label :'AccWip'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readProductAccount?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readProductAccount = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readProductAccount(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchProductAccount');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('ProductAccountReadPage',parameter);
    }    
    Promise.all([readProductAccount]).then(sendResult);
});

module.exports = router;
