/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRoomRead',
    Heading:'AppRoom',
    MeetingRoom:{label :'MeetingRoom'},
    Subject:{label :'Subject'},
    Participant:{label :'Participant'},
    StartDate:{label :'StartDate'},
    EndDate:{label :'EndDate'},
    Status:{label :'Status'},
    RefValue:{label :'RefValue'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppRoom?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppRoom = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppRoom(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppRoom');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppRoomReadPage',parameter);
    }    
    Promise.all([readAppRoom]).then(sendResult);
});

module.exports = router;
