/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppMessageRead',
    Heading:'AppMessage',
    Username:{label :'Username'},
    Jid:{label :'Jid'},
    Msgtime:{label :'Msgtime'},
    Msgtype:{label :'Msgtype'},
    Msgsubject:{label :'Msgsubject'},
    Msgtext:{label :'Msgtext'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppMessage?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppMessage = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppMessage(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppMessage');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppMessageReadPage',parameter);
    }    
    Promise.all([readAppMessage]).then(sendResult);
});

module.exports = router;
