/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppGroupsRead',
    Heading:'AppGroups',
    GroupId:{label :'GroupId'},
    GroupName:{label :'GroupName'},
    AppGroupAuthorities:{Heading:'AppGroupAuthorities',
        GroupId:{header:'GroupId'},
        Authority:{header:'Authority'},
        },
    AppGroupMembers:{Heading:'AppGroupMembers',
        GroupId:{header:'GroupId'},
        GroupMemberId:{header:'GroupMemberId'},
        Username:{header:'Username'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppGroups?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppGroups = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppGroups(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppGroups');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var appGroupAuthorities = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.searchAppGroupAuthorities(jsonObj,function(err,rows) {
                jsonObj.appGroupAuthorities = rows;
                resolve(jsonObj);
            });
        },1000);
    });
    
    var appGroupMembers = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.searchAppGroupMembers(jsonObj,function(err,rows) {
                jsonObj.appGroupMembers = rows;
                resolve(jsonObj);
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppGroupsReadPage',parameter);
    }    
    Promise.all([readAppGroups,appGroupAuthorities,appGroupMembers]).then(sendResult);
});

module.exports = router;
