/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AccountSectionRead',
    Heading:'AccountSection',
    Id:{label :'Id'},
    Name:{label :'Name'},
    Description:{label :'Description'},
    AccountGroup:{Heading:'AccountGroup',
        Id:{header:'Id'},
        Name:{header:'Name'},
        Parent:{header:'Parent'},
        Description:{header:'Description'},
        AccSectionId:{header:'AccSectionId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAccountSection?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAccountSection = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAccountSection(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAccountSection');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var accountGroup = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.searchAccountGroup(jsonObj,function(err,rows) {
                jsonObj.accountGroup = rows;
                resolve(jsonObj);
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AccountSectionReadPage',parameter);
    }    
    Promise.all([readAccountSection,accountGroup]).then(sendResult);
});

module.exports = router;
