/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'StockMasterRead',
    Heading:'StockMaster',
    Id:{label :'Id'},
    Code:{label :'Code'},
    Units:{label :'Units'},
    Mbflag:{label :'Mbflag'},
    Lastcurcostdate:{label :'Lastcurcostdate'},
    Actualcost:{label :'Actualcost'},
    Lastcost:{label :'Lastcost'},
    Materialcost:{label :'Materialcost'},
    Labourcost:{label :'Labourcost'},
    Overheadcost:{label :'Overheadcost'},
    Lowestlevel:{label :'Lowestlevel'},
    Discontinued:{label :'Discontinued'},
    Controlled:{label :'Controlled'},
    Eoq:{label :'Eoq'},
    Volume:{label :'Volume'},
    Kgs:{label :'Kgs'},
    Barcode:{label :'Barcode'},
    Discountcategory:{label :'Discountcategory'},
    Taxcatid:{label :'Taxcatid'},
    Serialised:{label :'Serialised'},
    Appendfile:{label :'Appendfile'},
    Perishable:{label :'Perishable'},
    Decimalplaces:{label :'Decimalplaces'},
    Nextserialno:{label :'Nextserialno'},
    Pansize:{label :'Pansize'},
    Shrinkfactor:{label :'Shrinkfactor'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readStockMaster?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readStockMaster = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readStockMaster(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchStockMaster');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('StockMasterReadPage',parameter);
    }    
    Promise.all([readStockMaster]).then(sendResult);
});

module.exports = router;
