/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'GeneralLedgerSearch',
    Heading:'GeneralLedger',
    Id:{label :'Id'},
    AccCode:{label :'AccCode'},
    CreateDate:{label :'CreateDate'},
    Description:{label :'Description'},
    Debit:{label :'Debit'},
    Credit:{label :'Credit'},
    Posted:{label :'Posted'},
    Source:{label :'Source'},
    GeneralLedger:{Heading:'GeneralLedger',
        Id:{header:'Id'},
        AccCode:{header:'AccCode'},
        CreateDate:{header:'CreateDate'},
        Description:{header:'Description'},
        Debit:{header:'Debit'},
        Credit:{header:'Credit'},
        Posted:{header:'Posted'},
        Source:{header:'Source'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchGeneralLedger?'+req._parsedUrl.query;
    dao.searchGeneralLedger(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('GeneralLedgerSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
