/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'StockMasterSearch',
    Heading:'StockMaster',
    Id:{label :'Id'},
    Code:{label :'Code'},
    Units:{label :'Units'},
    Mbflag:{label :'Mbflag'},
    Lastcurcostdate:{label :'Lastcurcostdate'},
    Actualcost:{label :'Actualcost'},
    Lastcost:{label :'Lastcost'},
    Materialcost:{label :'Materialcost'},
    Labourcost:{label :'Labourcost'},
    Overheadcost:{label :'Overheadcost'},
    Lowestlevel:{label :'Lowestlevel'},
    Discontinued:{label :'Discontinued'},
    Controlled:{label :'Controlled'},
    Eoq:{label :'Eoq'},
    Volume:{label :'Volume'},
    Kgs:{label :'Kgs'},
    Barcode:{label :'Barcode'},
    Discountcategory:{label :'Discountcategory'},
    Taxcatid:{label :'Taxcatid'},
    Serialised:{label :'Serialised'},
    Appendfile:{label :'Appendfile'},
    Perishable:{label :'Perishable'},
    Decimalplaces:{label :'Decimalplaces'},
    Nextserialno:{label :'Nextserialno'},
    Pansize:{label :'Pansize'},
    Shrinkfactor:{label :'Shrinkfactor'},
    StockMaster:{Heading:'StockMaster',
        Id:{header:'Id'},
        Code:{header:'Code'},
        Units:{header:'Units'},
        Mbflag:{header:'Mbflag'},
        Lastcurcostdate:{header:'Lastcurcostdate'},
        Actualcost:{header:'Actualcost'},
        Lastcost:{header:'Lastcost'},
        Materialcost:{header:'Materialcost'},
        Labourcost:{header:'Labourcost'},
        Overheadcost:{header:'Overheadcost'},
        Lowestlevel:{header:'Lowestlevel'},
        Discontinued:{header:'Discontinued'},
        Controlled:{header:'Controlled'},
        Eoq:{header:'Eoq'},
        Volume:{header:'Volume'},
        Kgs:{header:'Kgs'},
        Barcode:{header:'Barcode'},
        Discountcategory:{header:'Discountcategory'},
        Taxcatid:{header:'Taxcatid'},
        Serialised:{header:'Serialised'},
        Appendfile:{header:'Appendfile'},
        Perishable:{header:'Perishable'},
        Decimalplaces:{header:'Decimalplaces'},
        Nextserialno:{header:'Nextserialno'},
        Pansize:{header:'Pansize'},
        Shrinkfactor:{header:'Shrinkfactor'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchStockMaster?'+req._parsedUrl.query;
    dao.searchStockMaster(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('StockMasterSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
