/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ProductAccountSearch',
    Heading:'ProductAccount',
    Id:{label :'Id'},
    Code:{label :'Code'},
    Name:{label :'Name'},
    Description:{label :'Description'},
    Type:{label :'Type'},
    AccStock:{label :'AccStock'},
    AccAdjgl:{label :'AccAdjgl'},
    AccPurchase:{label :'AccPurchase'},
    AccMaterial:{label :'AccMaterial'},
    AccWip:{label :'AccWip'},
    ProductAccount:{Heading:'ProductAccount',
        Id:{header:'Id'},
        Code:{header:'Code'},
        Name:{header:'Name'},
        Description:{header:'Description'},
        Type:{header:'Type'},
        AccStock:{header:'AccStock'},
        AccAdjgl:{header:'AccAdjgl'},
        AccPurchase:{header:'AccPurchase'},
        AccMaterial:{header:'AccMaterial'},
        AccWip:{header:'AccWip'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchProductAccount?'+req._parsedUrl.query;
    dao.searchProductAccount(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('ProductAccountSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
