/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppAuthoritiesSearch',
    Heading:'AppAuthorities',
    Username:{label :'Username'},
    Authority:{label :'Authority'},
    AppAuthorities:{Heading:'AppAuthorities',
        Username:{header:'Username'},
        Authority:{header:'Authority'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppAuthorities?'+req._parsedUrl.query;
    dao.searchAppAuthorities(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppAuthoritiesSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
