/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppMessageSearch',
    Heading:'AppMessage',
    Username:{label :'Username'},
    Jid:{label :'Jid'},
    Msgtime:{label :'Msgtime'},
    Msgtype:{label :'Msgtype'},
    Msgsubject:{label :'Msgsubject'},
    Msgtext:{label :'Msgtext'},
    AppMessage:{Heading:'AppMessage',
        Username:{header:'Username'},
        Jid:{header:'Jid'},
        Msgtime:{header:'Msgtime'},
        Msgtype:{header:'Msgtype'},
        Msgsubject:{header:'Msgsubject'},
        Msgtext:{header:'Msgtext'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppMessage?'+req._parsedUrl.query;
    dao.searchAppMessage(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppMessageSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
