/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AccountMasterSearch',
    Heading:'AccountMaster',
    Id:{label :'Id'},
    AccCode:{label :'AccCode'},
    AccName:{label :'AccName'},
    AccDescription:{label :'AccDescription'},
    AccGroupId:{label :'AccGroupId'},
    AccountMaster:{Heading:'AccountMaster',
        Id:{header:'Id'},
        AccCode:{header:'AccCode'},
        AccName:{header:'AccName'},
        AccDescription:{header:'AccDescription'},
        AccGroupId:{header:'AccGroupId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAccountMaster?'+req._parsedUrl.query;
    dao.searchAccountMaster(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AccountMasterSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
