/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppMenusSearch',
    Heading:'AppMenus',
    Name:{label :'Name'},
    Link:{label :'Link'},
    Display:{label :'Display'},
    AppMenus:{Heading:'AppMenus',
        Name:{header:'Name'},
        Link:{header:'Link'},
        Display:{header:'Display'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppMenus?'+req._parsedUrl.query;
    dao.searchAppMenus(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppMenusSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
