/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ProductSearch',
    Heading:'Product',
    Id:{label :'Id'},
    Code:{label :'Code'},
    Parent:{label :'Parent'},
    Name:{label :'Name'},
    Description:{label :'Description'},
    DiscountCategory:{label :'DiscountCategory'},
    TaxId:{label :'TaxId'},
    Serialised:{label :'Serialised'},
    Product:{Heading:'Product',
        Id:{header:'Id'},
        Code:{header:'Code'},
        Parent:{header:'Parent'},
        Name:{header:'Name'},
        Description:{header:'Description'},
        DiscountCategory:{header:'DiscountCategory'},
        TaxId:{header:'TaxId'},
        Serialised:{header:'Serialised'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchProduct?'+req._parsedUrl.query;
    dao.searchProduct(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('ProductSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
