/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRoomSearch',
    Heading:'AppRoom',
    MeetingRoom:{label :'MeetingRoom'},
    Subject:{label :'Subject'},
    Participant:{label :'Participant'},
    StartDate:{label :'StartDate'},
    EndDate:{label :'EndDate'},
    Status:{label :'Status'},
    RefValue:{label :'RefValue'},
    AppRoom:{Heading:'AppRoom',
        MeetingRoom:{header:'MeetingRoom'},
        Subject:{header:'Subject'},
        Participant:{header:'Participant'},
        StartDate:{header:'StartDate'},
        EndDate:{header:'EndDate'},
        Status:{header:'Status'},
        RefValue:{header:'RefValue'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRoom?'+req._parsedUrl.query;
    dao.searchAppRoom(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRoomSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
