/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppContactSearch',
    Heading:'AppContact',
    Username:{label :'Username'},
    Subscription:{label :'Subscription'},
    Jid:{label :'Jid'},
    Nickname:{label :'Nickname'},
    Joindate:{label :'Joindate'},
    Show:{label :'Show'},
    Status:{label :'Status'},
    Lastseen:{label :'Lastseen'},
    Unread:{label :'Unread'},
    Key:{label :'Key'},
    AppContact:{Heading:'AppContact',
        Username:{header:'Username'},
        Subscription:{header:'Subscription'},
        Jid:{header:'Jid'},
        Nickname:{header:'Nickname'},
        Joindate:{header:'Joindate'},
        Show:{header:'Show'},
        Status:{header:'Status'},
        Lastseen:{header:'Lastseen'},
        Unread:{header:'Unread'},
        Key:{header:'Key'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppContact?'+req._parsedUrl.query;
    dao.searchAppContact(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppContactSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
