/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AccountGroupSearch',
    Heading:'AccountGroup',
    Id:{label :'Id'},
    Name:{label :'Name'},
    Parent:{label :'Parent'},
    Description:{label :'Description'},
    AccSectionId:{label :'AccSectionId'},
    AccountGroup:{Heading:'AccountGroup',
        Id:{header:'Id'},
        Name:{header:'Name'},
        Parent:{header:'Parent'},
        Description:{header:'Description'},
        AccSectionId:{header:'AccSectionId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAccountGroup?'+req._parsedUrl.query;
    dao.searchAccountGroup(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AccountGroupSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
