/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppGroupMembersSearch',
    Heading:'AppGroupMembers',
    GroupId:{label :'GroupId'},
    GroupMemberId:{label :'GroupMemberId'},
    Username:{label :'Username'},
    AppGroupMembers:{Heading:'AppGroupMembers',
        GroupId:{header:'GroupId'},
        GroupMemberId:{header:'GroupMemberId'},
        Username:{header:'Username'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppGroupMembers?'+req._parsedUrl.query;
    dao.searchAppGroupMembers(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppGroupMembersSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
