/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */
var request = require('request');

const sessionChecker = function(req, res, next){
  console.log(req.baseUrl);
  console.log(req.originalUrl);
  if (!req.session.loggedin) {
      res.redirect('/logout');
  } else {
      next();
  }    
};    

module.exports = sessionChecker;
