/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'ProductAccountWrite',
    Heading:'ProductAccount',
    Id:{label :'Id'},
    Code:{label :'Code'},
    Name:{label :'Name'},
    Description:{label :'Description'},
    Type:{label :'Type'},
    AccStock:{label :'AccStock'},
    AccAdjgl:{label :'AccAdjgl'},
    AccPurchase:{label :'AccPurchase'},
    AccMaterial:{label :'AccMaterial'},
    AccWip:{label :'AccWip'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readProductAccount(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('ProductAccountWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeProductAccount(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('ProductAccountWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
